#452 Updated Identifier tool to be a separated floating tool
NASA-AMMOS/MMGIS pull request #453
Opened 2023-11-13 19:46 UTC by jtroberts

## Purpose
- Updated Identifier tool to be a separated floating tool
## Proposed Changes
## Issues
- #452 
## Testing
- Currently being used by one mission and works as expected with tools on the right-side of the UI
- Clicking on tool icon activates tool, allows user to hover over data to see values, tool remains activated with Layer tool open and user switching between layers, clicking again on tool icon deactivates tool

- Need to test different UI combinations with other separated tools
- We may possibly want an option to make the tool not be separated to maintain compatibility

2023-11-13 21:29 UTC, tariqksoliman requested changes
Looks good to me but it really needs to be backwards compatible too. Before I saved the configuration again (to make the IdentifierTool default to separated), clicking on the IdentifierTool in the toolbar made it impossible to open any other tool afterwards.

2024-04-23 17:12 UTC, tariqksoliman approved these changes
Looks good to me!
Though I keep seem to justify it to the right unless the legend is also justified to the right.

2024-04-25 21:33 UTC, jtroberts commented
I added support to allow the Identifier and Legend tools to be on different sides if specified. We may need a more scalable though, if we enable more separated tools in the future.

2024-04-25 21:34 UTC, tariqksoliman approved these changes
Okay, looks completely good to me now then.

2024-04-25 21:43 UTC, merged