New Feature to add symbols and dynamic colors
NASA-AMMOS/MMGIS pull request #84
Opened 2021-07-27 01:10 UTC by Ricecrackerz

Implemented:
-A dropdown bar to choose a shape for a layer (a point on the map) in the config page
-Shapes such as: Triangle, Square, Circle, Star, Hexagon, and Dinosaur
-Changed the selected stroke color to white
-Edited the props:color code to let symbols have a fill color based on some database
-Added a triangle shape to the Legends.js file to display a Triangle.

2021-07-27 01:18 UTC, jtroberts commented on src/essence/Basics/Map_/Map_.js
> +                    if(true){
I think you can get rid of this if statement and the console log message below.

2021-07-27 02:02 UTC, jtroberts approved these changes

2021-07-27 17:38 UTC, tariqksoliman requested changes
Nice work!

I think we really need a "none" type (which is the default (not "circle")) that uses the previous `L.circleMarker` class. Just so that everything existing works the same way.

You should also use the rest of the style properties in the svgs:

- stroke = Stroke Color
- stroke-width = Stroke Weight
- opacity = Fill Opacity
- r = Radius (a bit trickier than the rest too since you need to change the width and height style props as well)

And, as much as it pains me to say, the dinosaurs are going to have to go extinct.

2021-08-03 18:42 UTC, tariqksoliman approved these changes
LGTM

2021-08-03 22:00 UTC, merged